### PR TITLE
Alternative way to get own public IP

### PR DESCRIPTION
**Pull request by JulyIGHOR**
this ```dig +short myip.opendns.com @resolver1.opendns.com``` shows ip of ISP, not yours, if they replace your DNS requests.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks! I have changed this a little bit and will merge it now.

**Comment by JulyIGHOR** [comment]
I'm using iTerm 2 on macOS, and if I remove "&& echo" I'm getting this output:

**Comment by herrbischoff** [comment]
Ah, okay. Bash appears not to insert a newline on its own. Very inconvenient.

**Comment by NoahCardoza** [comment]
Yeah, it does seem a little odd. If you ever need to discern the exact character output (especially for hidden characters) just pip the output through `cat -e` it will display hidden characters as other symbols. Use man for more info. 

I would suggest you add a newline to your prompt, or you could check out [ZSH](https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH)

**Comment by herrbischoff** [comment]
As long as we're on the topic of shells: I'm a fish convert. It's not exactly POSIX compliant but it is what it says on the tin:

> Finally, a command line shell for the 90s

🤣 

https://fishshell.com/

**Comment by herrbischoff** [comment]
Back on topic, I just tried the full contents of my `/etc/shells` file:

* `sh`
* `csh`
* `tcsh`
* `ksh`
* `bash`
* `zsh`
* `fish`

With the exception of `zsh` and `fish`, all exhibit the same behavior, so I guess the trailing `echo` is (sadly) justified.

**Pull request merged**
