### PR TITLE
Add "Lock the Dock Size"

### PR DESCRIPTION
**Pull request by mhumeSF**
For anyone who has to repeatedly run osx defaults to reset dock size

https://www.macobserver.com/tmo/article/how-to-lock-the-dock-size-position-and-contents-in-os-x

### CODE REVIEW

**Comment by MindTooth** [comment]
I use this at every re-install.

**Comment by mhumeSF** [comment]
Is there something wrong with this PR?

**Comment by herrbischoff** [comment]
On the contrary, everything is fine with it, I just didn't find the time to review the open PRs. Merged it now.

**Comment by mhumeSF** [comment]
Many thanks!

**Pull request merged**
